### ISSUE TITLE
Bug: "Provider returned invalid result object after apply" after applying an in-place update to `timescale_service`

### ISSUE THREAD

**Issue by mattk-ce** [timescale/terraform-provider-timescale#208]
```
│ Error: Provider returned invalid result object after apply
│
│ After the apply operation, the provider still indicated an unknown value
│ for timescale_service.RESOURCE_NAME.password. All values must be known after apply,
│ so this is always a bug in the provider and should be reported in the
│ provider's own repository. Terraform will still save the other known object
│ values in the state.
```

**Comment by dennisameling** [comment]
We're running into the same error when changing the `memory_gb` and `milli_cpu` values on an already existing database:

```terraform
  # timescale_service.database will be updated in-place
  ~ resource "timescale_service" "database" {
      ~ hostname                  = "REDACTED.vpc.tsdb.forge.timescale.com" -> (known after apply)
        id                        = "REDACTED"
      ~ memory_gb                 = 128 -> 64
      ~ milli_cpu                 = 32000 -> 16000
        name                      = "production-tsdb"
      + password                  = (sensitive value)
      + pooler_hostname           = (known after apply)
      + pooler_port               = (known after apply)
      ~ port                      = 5432 -> (known after apply)
      + replica_hostname          = (known after apply)
      + replica_port              = (known after apply)
        # (7 unchanged attributes hidden)
    }
```

This results in the exact same error as the issue author reported, about the password not being available.

I think the problem here might be that this Terraform provider only outputs the password at service creation. From the [docs](https://registry.terraform.io/providers/timescale/timescale/latest/docs/resources/service#password):

> The password is provided once during service creation

We store this password in an AWS secret after creation, but this seems to cause problems when doing an in-place update on a running instance. If we could provide our own password upfront and pass it to the resource, that would also work, unless the Timescale team has a better approach. Thanks!

**Comment by Khyme** [comment]
the [v1.12.0](https://github.com/timescale/terraform-provider-timescale/releases/tag/v1.12.0) provider release makes password a configurable attribute and should ultimately solve the import issue observed
